name: Python Tests

on:
 push:
    branches:
      - master
 pull_request:
    branches:
      - master

jobs:
 test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11, 3.12]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U coveralls twine wheel
        pip install -r requirements.txt
    - name: Run tests
      run: |
        coverage run --branch pedantic/tests/tests_main.py
    - name: Coveralls
      uses: coverallsapp/github-action@v2.2.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        file: .coverage
    - name: Build and Upload ti PyPI
      run: |
        python setup.py bdist_wheel
        twine upload dist/*.whl  # Uploads the wheel file to PyPI
